# Generated by Django 2.2.12 on 2020-05-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200510_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_word',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
